DigiXchange/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

DigiXchange/digixchange/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView



from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page, encrypt, decrypt

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^register/$', register_page, name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^admin/', admin.site.urls),

    url(r'^encrypt/', encrypt, name='encrypt'),
    url(r'^decrypt/', decrypt, name='decrypt'),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)












































#end

DigiXchange/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'encrypt' as encyrpt_url %}
{% url 'decrypt' as decrypt_url %}
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="{% static 'img/digitalx.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    {% if brand_name %} {{brand_name }} {% else %}DigiXchange {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <!-- <li class="nav-item {% if request.path == encrypt_url %}active{% endif %} ">
          <a class="nav-link" href="{{ encyrpt_url }}">Encyrpt</a>
      </li>
      <li class="nav-item {% if request.path == decrypt_url %}active{% endif %} ">
          <a class="nav-link" href="{{ decrypt_url }}">Decrypt</a>
      </li> -->

      {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"> {{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>

       <!--  <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown link
            </a>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> -->

    </ul>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>